defaults:
  - algorithm: gcs_astar_reachability
  - cost_estimator: shortcut_edge
  - domination_checker: reaches_new_last_pos_sampling
  - hydra: hydra
  - source: point_6
  - target: point_8


graph_name: "ggcs_new"

cost_estimator:
  # USE L1 NORM SHORTCUT EDGE COST
  shortcut_edge_cost_factory: large_gcs.graph.cfree_cost_constraint_factory.create_cfree_shortcut_edge_factory_translation_weighted_over

save_visualization: true
save_solution: true
save_metrics: true
save_to_wandb: false

algorithm:
  should_invert_S: true
  should_terminate_early: true
  allow_cycles: false

domination_checker:
  num_samples_per_vertex: 1
  should_use_candidate_sol: false


hydra:
  mode: MULTIRUN
  sweeper:
    params: 
      # Test with just 2 points
      # source: point_6, point_8
      # target: point_6, point_8
      # Test with all 9 points
      source: point_0, point_1, point_2, point_3, point_4, point_5, point_6, point_7, point_8
      target: point_0, point_1, point_2, point_3, point_4, point_5, point_6, point_7, point_8
      # source: point_0
      # target: point_1
